// src/pages/NotFound.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import Header from '../components/Header.jsx';
import Footer from '../components/Footer.jsx';

const NotFound = () => {
  return (
    <>
      <style>{`
        /* Global variables are now in main.css */
        
        /* Root Variables - Enhanced for 404 page */
        :root {
          --primary-cyan: #00D4FF;
          --primary-blue: #4F46E5;
          --primary-purple: #9333EA;
          --gradient-primary: linear-gradient(135deg, var(--primary-cyan) 0%, var(--primary-blue) 50%, var(--primary-purple) 100%);
          --neutral-white: #FAFBFC;
          --pure-white: #ffffff;
          --text-color: #000000;
          --background: var(--neutral-white);
          --gray-600: #6c757d;
          --gray-700: #495057;
          --gray-800: #343a40;
          --gray-900: #212529;
          --shadow-sm: 0 1px 3px 0 rgba(0, 212, 255, 0.1), 0 1px 2px 0 rgba(0, 212, 255, 0.06);
          --shadow-md: 0 4px 6px -1px rgba(0, 212, 255, 0.1), 0 2px 4px -1px rgba(0, 212, 255, 0.06);
          --shadow-lg: 0 10px 15px -3px rgba(0, 212, 255, 0.1), 0 4px 6px -2px rgba(0, 212, 255, 0.05);
          --shadow-glow: 0 0 20px rgba(0, 212, 255, 0.3);
        }
        /* Base Styles */
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
        }
        
        body {
          font-family: 'Montserrat', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          background: var(--background);
          color: var(--text-color);
          line-height: 1.6;
          overflow-x: hidden;
          font-size: 16px;
          transition: background-color 0.3s ease, color 0.3s ease;
        }
        
        h1, h2, h3, h4, h5, h6 {
          font-family: 'Space Grotesk', sans-serif;
          color: var(--text-color);
          margin: 0 0 1.5rem;
          text-align: center;
          transition: color 0.3s ease;
        }
        
        /* Dark mode styles */
        @media (prefers-color-scheme: dark) {
          :root {
            --neutral-white: #1E1E1E;
            --background: #1E1E1E;
            --text-color: #F9F9F9;
            --gray-600: #9ca3af;
            --gray-700: #6b7280;
          }
          
          .not-found-text {
            color: var(--gray-600) !important;
          }
          
          .not-found-image {
            filter: brightness(0.9) contrast(1.1);
          }
        }
        /* Not Found Specific Styles */
        .not-found-container {
          min-height: 100vh;
          background: var(--background);
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          padding: 6rem 2rem 2rem 2rem;
          position: relative;
          overflow: hidden;
        }
        
        .not-found-content {
          text-align: center;
          max-width: 48rem;
          margin: 0 auto;
          position: relative;
          z-index: 2;
        }
        
        .not-found-image-container {
          margin-bottom: 2rem;
          display: flex;
          justify-content: center;
          align-items: center;
        }
        
        .not-found-image {
          max-width: 300px;
          width: 100%;
          height: auto;
          border-radius: 16px;
          box-shadow: var(--shadow-lg);
          transition: all 0.3s ease;
        }
        
        .not-found-image:hover {
          transform: scale(1.02);
          box-shadow: var(--shadow-glow);
        }
        
        .not-found-404 {
          font-size: clamp(4rem, 12vw, 8rem);
          font-weight: 800;
          background: var(--gradient-primary);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
          margin-bottom: 1rem;
          line-height: 1;
          letter-spacing: -0.02em;
        }
        
        .not-found-title {
          font-size: clamp(1.5rem, 4vw, 2.5rem);
          font-weight: 700;
          color: var(--gray-900);
          margin-bottom: 1rem;
          line-height: 1.2;
          letter-spacing: -0.01em;
        }
        
        .not-found-text {
          font-size: clamp(1rem, 2.5vw, 1.25rem);
          color: var(--gray-600);
          margin-bottom: 2.5rem;
          line-height: 1.6;
          max-width: 600px;
          margin-left: auto;
          margin-right: auto;
        }
        
        .not-found-button {
          display: inline-flex;
          align-items: center;
          gap: 0.5rem;
          padding: 1rem 2rem;
          background: var(--gradient-primary);
          color: var(--pure-white) !important;
          font-weight: 600;
          font-size: 1rem;
          border-radius: 12px;
          text-decoration: none;
          transition: all 0.3s ease;
          box-shadow: var(--shadow-md);
          border: none;
          cursor: pointer;
          line-height: 1.25;
          position: relative;
          overflow: hidden;
        }
        
        .not-found-button::before {
          content: '';
          position: absolute;
          top: 0;
          left: -100%;
          width: 100%;
          height: 100%;
          background: linear-gradient(90deg, transparent, rgba(255,255,255,0.2), transparent);
          transition: left 0.5s ease;
        }
        
        .not-found-button:hover::before {
          left: 100%;
        }
        
        .not-found-button:hover {
          transform: translateY(-3px);
          box-shadow: var(--shadow-lg), var(--shadow-glow);
          filter: brightness(1.1);
        }
        
        .not-found-button:active {
          transform: translateY(-1px);
        }
        
        .not-found-background {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: radial-gradient(circle at 30% 20%, rgba(0, 212, 255, 0.1) 0%, transparent 50%),
                      radial-gradient(circle at 70% 80%, rgba(79, 70, 229, 0.1) 0%, transparent 50%),
                      radial-gradient(circle at 90% 10%, rgba(147, 51, 234, 0.1) 0%, transparent 50%);
          z-index: 1;
        }
        
        /* Mobile Optimizations */
        @media (max-width: 768px) {
          .not-found-container {
            padding: 5rem 1rem 2rem 1rem;
          }
          
          .not-found-image {
            max-width: 250px;
          }
          
          .not-found-button {
            padding: 0.875rem 1.5rem;
            font-size: 0.9375rem;
          }
        }
        
        @media (max-width: 480px) {
          .not-found-container {
            padding: 4rem 1rem 2rem 1rem;
          }
          
          .not-found-image {
            max-width: 200px;
          }
          
          .not-found-button {
            width: 100%;
            max-width: 280px;
            justify-content: center;
          }
        }
      `}</style>
      <Header />
      <div className="not-found-container">
        <div className="not-found-background"></div>
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, ease: "easeOut" }}
          className="not-found-content"
        >
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="not-found-image-container"
          >
            <img
              src="/assets/images/404/image.png"
              alt="Page Not Found"
              className="not-found-image"
            />
          </motion.div>

          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.5 }}
            className="not-found-title"
          >
            Oops! Page Not Found
          </motion.h2>

          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6 }}
            className="not-found-text"
          >
            The page you're looking for seems to have wandered off into the digital wilderness.
            Don't worry though – let's get you back on track to discover amazing wellness tools and insights.
          </motion.p>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.7 }}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
          >
            <Link
              to="/"
              className="not-found-button"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z"
                  clipRule="evenodd"
                />
              </svg>
              Return Home
            </Link>
          </motion.div>
        </motion.div>
      </div>
      <Footer />
    </>
  );
};

export default NotFound;

// src/pages/NotFound.svelte
<script>
  import Button from "../components/ui/Button.svelte";
  import { navigateToHome } from "../lib/stores/router.js";

  function handleGoHome() {
    navigateToHome();
  }

  function handleGoBack() {
    if (window.history.length > 1) {
      window.history.back();
    } else {
      navigateToHome();
    }
  }
</script>

<div class="page page--not-found">
  <!-- 404 Hero Section -->
  <section class="not-found-hero">
    <div class="not-found-hero__container">
      <div class="not-found-hero__content">
        <div class="not-found-hero__visual">
          <!-- Abstract 404 illustration -->
          <svg
            class="not-found-hero__svg"
            viewBox="0 0 400 300"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <!-- Broken path/connection illustration -->
            <path
              d="M50 150 Q100 100 150 150 T250 150"
              stroke="currentColor"
              stroke-width="3"
              stroke-dasharray="10,5"
              opacity="0.4"
              fill="none"
            />
            <path
              d="M250 150 Q300 100 350 150"
              stroke="currentColor"
              stroke-width="3"
              stroke-dasharray="10,5"
              opacity="0.2"
              fill="none"
            />
            
            <!-- Disconnected nodes -->
            <circle cx="50" cy="150" r="8" fill="currentColor" opacity="0.6" />
            <circle cx="150" cy="150" r="8" fill="currentColor" opacity="0.8" />
            <circle cx="250" cy="150" r="8" fill="currentColor" />
            <circle cx="350" cy="150" r="6" fill="currentColor" opacity="0.3" />
            
            <!-- Question mark symbol -->
            <circle cx="200" cy="80" r="25" fill="none" stroke="currentColor" stroke-width="2" opacity="0.5" />
            <path d="M190 70 Q200 60 210 70 Q210 80 200 85 M200 95 L200 100" stroke="currentColor" stroke-width="2" opacity="0.7" fill="none" />
            
            <!-- Floating geometric shapes -->
            <rect x="80" y="50" width="15" height="15" fill="currentColor" opacity="0.3" transform="rotate(45 87.5 57.5)" />
            <circle cx="320" cy="80" r="6" fill="currentColor" opacity="0.4" />
            <polygon points="100,220 115,240 85,240" fill="currentColor" opacity="0.3" />
          </svg>
        </div>
        
        <div class="not-found-hero__text">
          <h1 class="not-found-hero__title">
            <span class="not-found-hero__title-number">404</span>
            <span class="not-found-hero__title-main">Page Not Found</span>
          </h1>
          <p class="not-found-hero__subtitle">
            The page you're looking for seems to have wandered off into the digital void. 
            Don't worry—even the best explorers sometimes take a wrong turn.
          </p>
        </div>
      </div>
    </div>
  </section>

  <!-- Suggestions Section -->
  <section class="suggestions">
    <div class="suggestions__container">
      <div class="suggestions__content">
        <h2 class="suggestions__title">Let's get you back on track</h2>
        
        <div class="suggestions__grid">
          <div class="suggestion-card">
            <div class="suggestion-card__icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M3 9L12 2L21 9V20C21 20.5304 20.7893 21.0391 20.4142 21.4142C20.0391 21.7893 19.5304 22 19 22H5C4.46957 22 3.96086 21.7893 3.58579 21.4142C3.21071 21.0391 3 20.5304 3 20V9Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                <path d="M9 22V12H15V22" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="suggestion-card__title">Go Home</h3>
            <p class="suggestion-card__description">
              Start fresh from our homepage and explore what Alelken has to offer.
            </p>
          </div>

          <div class="suggestion-card">
            <div class="suggestion-card__icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M19 12H5M12 19L5 12L12 5" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="suggestion-card__title">Go Back</h3>
            <p class="suggestion-card__description">
              Return to the previous page and continue your journey from there.
            </p>
          </div>

          <div class="suggestion-card">
            <div class="suggestion-card__icon">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
                <path d="M21 21L16.514 16.506L21 21ZM19 10.5C19 15.194 15.194 19 10.5 19C5.806 19 2 15.194 2 10.5C2 5.806 5.806 2 10.5 2C15.194 2 19 5.806 19 10.5Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
            </div>
            <h3 class="suggestion-card__title">Explore</h3>
            <p class="suggestion-card__description">
              Check out our Product, Press releases, or learn more About us.
            </p>
            <div class="suggestion-card__links">
              <a href="#product" class="suggestion-link">Product</a>
              <a href="#press" class="suggestion-link">Press</a>
              <a href="#about" class="suggestion-link">About</a>
            </div>
          </div>
        </div>

        <div class="suggestions__actions">
          <Button variant="primary" on:click={handleGoHome}>
            Take Me Home
          </Button>
          <Button variant="secondary" on:click={handleGoBack}>
            Go Back
          </Button>
        </div>
      </div>
    </div>
  </section>
</div>

<style>
  .page {
    flex: 1;
    padding-top: 4rem;
    background: linear-gradient(135deg, var(--color-night) 0%, #1a2b28 100%);
    min-height: 100vh;
  }

  /* 404 Hero Section */
  .not-found-hero {
    padding: var(--space-24) 0 var(--space-20) 0;
    position: relative;
    overflow: hidden;
  }

  .not-found-hero__container {
    max-width: var(--container-max-width);
    margin: 0 auto;
    padding: 0 var(--container-padding);
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: var(--space-20);
    align-items: center;
  }

  .not-found-hero__visual {
    display: flex;
    justify-content: center;
    align-items: center;
    order: 2;
  }

  .not-found-hero__svg {
    width: 100%;
    max-width: 400px;
    height: auto;
    color: var(--color-olive-light);
  }

  .not-found-hero__text {
    order: 1;
  }

  .not-found-hero__title {
    font-family: var(--font-heading);
    font-weight: var(--weight-bold);
    line-height: var(--leading-tight);
    margin: 0 0 var(--space-6) 0;
  }

  .not-found-hero__title-number {
    display: block;
    font-size: var(--text-6xl);
    color: var(--color-olive-light);
    margin-bottom: var(--space-2);
    font-weight: var(--weight-bold);
  }

  .not-found-hero__title-main {
    display: block;
    font-size: var(--text-4xl);
    color: var(--color-white-warm);
    background: linear-gradient(135deg, var(--color-white-warm) 0%, rgba(254, 253, 251, 0.8) 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
  }

  .not-found-hero__subtitle {
    font-family: var(--font-body);
    font-size: var(--text-xl);
    color: rgba(254, 253, 251, 0.85);
    line-height: var(--leading-relaxed);
    margin: 0;
    max-width: 32rem;
  }

  /* Suggestions Section */
  .suggestions {
    background: rgba(47, 62, 59, 0.6);
    padding: var(--space-20) 0;
  }

  .suggestions__container {
    max-width: var(--container-max-width);
    margin: 0 auto;
    padding: 0 var(--container-padding);
  }

  .suggestions__content {
    text-align: center;
  }

  .suggestions__title {
    font-family: var(--font-heading);
    font-size: var(--text-3xl);
    font-weight: var(--weight-bold);
    color: var(--color-white-warm);
    margin: 0 0 var(--space-16) 0;
  }

  .suggestions__grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: var(--space-8);
    margin-bottom: var(--space-16);
  }

  .suggestion-card {
    background: rgba(139, 126, 83, 0.1);
    border: 1px solid rgba(139, 126, 83, 0.2);
    border-radius: 1rem;
    padding: var(--space-8);
    text-align: center;
    transition: all 400ms ease;
  }

  .suggestion-card:hover {
    background: rgba(139, 126, 83, 0.15);
    transform: translateY(-4px);
    box-shadow: 0 8px 24px rgba(47, 62, 59, 0.3);
  }

  .suggestion-card__icon {
    width: 60px;
    height: 60px;
    border-radius: 50%;
    background: var(--color-olive-light);
    color: var(--color-night);
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto var(--space-6) auto;
  }

  .suggestion-card__title {
    font-family: var(--font-heading);
    font-size: var(--text-xl);
    font-weight: var(--weight-bold);
    color: var(--color-white-warm);
    margin: 0 0 var(--space-4) 0;
  }

  .suggestion-card__description {
    font-family: var(--font-body);
    font-size: var(--text-base);
    color: rgba(254, 253, 251, 0.85);
    line-height: var(--leading-relaxed);
    margin: 0 0 var(--space-4) 0;
  }

  .suggestion-card__links {
    display: flex;
    gap: var(--space-2);
    justify-content: center;
    flex-wrap: wrap;
  }

  .suggestion-link {
    font-family: var(--font-body);
    font-size: var(--text-sm);
    font-weight: var(--weight-medium);
    color: var(--color-olive-light);
    text-decoration: none;
    padding: var(--space-1) var(--space-3);
    border: 1px solid var(--color-olive-light);
    border-radius: 1rem;
    transition: all 200ms ease;
  }

  .suggestion-link:hover {
    background-color: var(--color-olive-light);
    color: var(--color-night);
    transform: translateY(-1px);
  }

  .suggestions__actions {
    display: flex;
    justify-content: center;
    gap: var(--space-4);
    flex-wrap: wrap;
  }

  /* Responsive Design */
  @media (max-width: 1023px) {
    .not-found-hero__container {
      grid-template-columns: 1fr;
      gap: var(--space-16);
      text-align: center;
    }

    .not-found-hero__visual {
      order: 1;
    }

    .not-found-hero__text {
      order: 2;
    }
  }

  @media (max-width: 767px) {
    .page {
      padding-top: 3.5rem;
    }

    .not-found-hero {
      padding: var(--space-16) 0;
    }

    .not-found-hero__title-number {
      font-size: var(--text-5xl);
    }

    .not-found-hero__title-main {
      font-size: var(--text-3xl);
    }

    .not-found-hero__subtitle {
      font-size: var(--text-lg);
    }

    .suggestions {
      padding: var(--space-16) 0;
    }

    .suggestions__title {
      font-size: var(--text-2xl);
    }

    .suggestions__grid {
      grid-template-columns: 1fr;
      gap: var(--space-6);
    }

    .suggestions__actions {
      flex-direction: column;
      align-items: center;
    }

    .suggestions__actions :global(.btn) {
      width: 100%;
      max-width: 280px;
    }
  }

  @media (max-width: 479px) {
    .not-found-hero__title-number {
      font-size: var(--text-4xl);
    }

    .not-found-hero__title-main {
      font-size: var(--text-2xl);
    }

    .suggestion-card {
      padding: var(--space-6);
    }
  }
</style>
